site_name: esp3d.io
site_description: ESP3D Ecosystem documentation
site_url: https://esp3d.io
repo_url: 'https://github.com/luc-github/esp3d.io'
edit_uri_template: 'edit/main/src/content/{path}'

nav:
  - Introduction: 'index.md'

plugins:
  - mermaid2
  
theme:
    name: readthedocs
    custom_dir: custom_theme/
    navigation_depth: 1
    titles_only: false
    sticky_navigation: false
    collapse_navigation: true
    logo: /img/ESP3D_mini2.png


