site_name: esp3d.io
site_description: ESP3D Ecosystem documentation
site_url: https://esp3d.io
repo_url: 'https://github.com/luc-github/esp3d.io'
edit_uri_template: 'edit/main/src/content/{path}'
copyright: 'Copyright &copy; Luc LEBOSSE 2022 ESP3D'

nav:
- index.md
- ESP3D: 
  - ESP3D/index.md  
  - Version 2.1.X:
        - ESP3D/Version_2.1.X/index.md
        - ESP3D/Version_2.1.X/credits/index.md
        - ESP3D/Version_2.1.X/features/index.md
        - Hardware:
            - ESP3D/Version_2.1.X/hardware/index.md
            - ESP8266:
                - ... | flat | ESP3D/Version_2.1.X/hardware/ESP8266/**
            - ESP8285:
                - ... | flat | ESP3D/Version_2.1.X/hardware/ESP8285/**
            - ESP32:
                - ... | flat | ESP3D/Version_2.1.X/hardware/ESP32/**
        - Installation:
            - ESP3D/Version_2.1.X/installation/index.md
        - Documentation:
            -  ESP3D/Version_2.1.X/documentation/index.md
            -  ESP3D/Version_2.1.X/documentation/commands/index.md
            - Notifications:
              -  ESP3D/Version_2.1.X/documentation/notifications/index.md
              -  ESP3D/Version_2.1.X/documentation/notifications/pushover.md
              -  ESP3D/Version_2.1.X/documentation/notifications/line.md
              -  ESP3D/Version_2.1.X/documentation/notifications/email_and_smtp.md
              -  ESP3D/Version_2.1.X/documentation/notifications/ifttt.md
            -  ESP3D/Version_2.1.X/documentation/sdtransfert/index.md
            -  ESP3D/Version_2.1.X/documentation/api/index.md
        - ESP3D/Version_2.1.X/showcase/index.md
not_in_nav:
  /common

plugins:
  - glightbox
  - awesome-pages
  - mermaid2
  - search:
      min_search_length: 2
  - autorefs
  - include-markdown
  - section-index
  - macros
  
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __s pan
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
          
          
  
theme:
    name: readthedocs
    custom_dir: custom_theme/
    navigation_depth: 12
    titles_only: true
    sticky_navigation: false
    collapse_navigation: true
    logo: /img/ESP3D_mini2.png



